services:
  monerod:
    container_name: monerod
    image: monerod:latest
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 30m1s
    stop_signal: SIGTERM
    volumes:
      - ./config:/config:ro
